tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "buo/cask-upgrade"
tap "ethereum/ethereum"
tap "getsentry/tools"

brew "alerter"
brew "ansible"
brew "ccls"
brew "cmake"
brew "direnv"
brew "getsentry/tools/sentry-cli"
brew "git-lfs"
brew "github-keygen"
brew "gh"
brew "gnupg"
brew "jq"
brew "jupyterlab"
brew "mas"
brew "nodenv"
brew "neovim"
brew "postgresql@14"
brew "pyenv"
brew "socat"
brew "solidity"
brew "terraform"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "zsh-completions"

cask "1password"
cask "actual"
cask "airtable"
cask "alfred"
cask "brave-browser"
cask "calibre"
cask "charles"
cask "chatterino"
cask "clay"
cask "daisydisk"
cask "dash"
cask "discord"
cask "dropbox"
cask "electron-fiddle"
cask "fantastical"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "inkscape"
cask "iterm2"
cask "keycastr"
cask "kindle" # todo - where are you?
cask "kindle-previewer" # todo - where are you?
cask "krisp"
cask "little-snitch"
cask "loom"
cask "mimestream"
cask "microsoft-teams"
cask "notion"
cask "obs"
cask "obsidian"
cask "raycast"
cask "screenflow"
cask "scrivener"
cask "signal"
cask "skim"
cask "slack"
cask "spotify"
cask "steam"
cask "telegram"
cask "tor-browser"
cask "transmission"
cask "unpkg"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"
cask "whatsapp"
cask "zoom"
cask "zotero"

mas "XCode", id: 497799835
mas "Shush - Microphone Manager", id: 496437906
mas "Magnet", id: 441258766
